//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoesDE.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.Content = new HashSet<Content>();
        }
    
        public int idOrder { get; set; }
        public System.DateTime dateOrder { get; set; }
        public System.DateTime dateDelivery { get; set; }
        public int idPoint { get; set; }
        public int idUser { get; set; }
        public int code { get; set; }
        public int idStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Content> Content { get; set; }
        public virtual Point Point { get; set; }
        public virtual Status Status { get; set; }
        public virtual User User { get; set; }
    }
}
