//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoesDE.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Content = new HashSet<Content>();
        }
    
        public int idProduct { get; set; }
        public string article { get; set; }
        public int idNameProduct { get; set; }
        public int idUnit { get; set; }
        public float cost { get; set; }
        public int idProvider { get; set; }
        public int idManufacturer { get; set; }
        public int idCategory { get; set; }
        public Nullable<int> sale { get; set; }
        public int count { get; set; }
        public string description { get; set; }
        public string photo { get; set; }
    
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Content> Content { get; set; }
        public virtual Manufacturer Manufacturer { get; set; }
        public virtual nameProduct nameProduct { get; set; }
        public virtual Provider Provider { get; set; }
        public virtual Unit Unit { get; set; }
    }
}
